name: Get Repositories

on:
  workflow_dispatch:

jobs:
  get-repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Repository Names
        id: get-repos
        run: |
          gh api --paginate '/user/repos' --jq '.[].full_name' > repositories.txt
          # Replace '/user/repos' with the appropriate endpoint for organization repositories if needed

      - name: Display Repository Names
        run: |
          cat repositories.txt
